// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIW25TfU7lC5se09ava735E2JF_5DQpck',
    appId: '1:240137581207:web:5a2065185399cfc1eaafd2',
    messagingSenderId: '240137581207',
    projectId: 'flutter-ecommerce-app-1ee43',
    authDomain: 'flutter-ecommerce-app-1ee43.firebaseapp.com',
    storageBucket: 'flutter-ecommerce-app-1ee43.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDm89IXek_SV52NuJAoCVTkdiSaBmcsGyw',
    appId: '1:240137581207:android:70678afec1dd43caeaafd2',
    messagingSenderId: '240137581207',
    projectId: 'flutter-ecommerce-app-1ee43',
    storageBucket: 'flutter-ecommerce-app-1ee43.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7OrSvO7pU0jWekbW4ok5SNLrxXb7n8EA',
    appId: '1:240137581207:ios:803801d07bb7108deaafd2',
    messagingSenderId: '240137581207',
    projectId: 'flutter-ecommerce-app-1ee43',
    storageBucket: 'flutter-ecommerce-app-1ee43.appspot.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7OrSvO7pU0jWekbW4ok5SNLrxXb7n8EA',
    appId: '1:240137581207:ios:803801d07bb7108deaafd2',
    messagingSenderId: '240137581207',
    projectId: 'flutter-ecommerce-app-1ee43',
    storageBucket: 'flutter-ecommerce-app-1ee43.appspot.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIW25TfU7lC5se09ava735E2JF_5DQpck',
    appId: '1:240137581207:web:42da5dbf4684b5f5eaafd2',
    messagingSenderId: '240137581207',
    projectId: 'flutter-ecommerce-app-1ee43',
    authDomain: 'flutter-ecommerce-app-1ee43.firebaseapp.com',
    storageBucket: 'flutter-ecommerce-app-1ee43.appspot.com',
  );
}
